plugins {
    id "com.android.application"
    id "com.chaquo.python"
}

android {
    namespace "org.p2p6024.android"
    compileSdk 35

    defaultConfig {
        applicationId "org.p2p6024.android"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "0.1.0"

        ndk {
            abiFilters "arm64-v8a", "x86_64"
        }
    }
}

chaquopy {
    defaultConfig {
        version = "3.13"
        pip {
            install("cryptography>=42,<51")
        }
    }
    sourceSets {
        getByName("main") {
            srcDir("../../src")
            srcDir("src/main/python")
        }
    }
}
